### ISSUE TITLE
GPL v3 License violation

### ISSUE THREAD

**Issue by esoteric-programmer** [kspalaiologos/malbolge-lisp#3]
This is great work, no doubt.

However, it cannot be released under C0, because it contains the init_module string from LMFAO https://github.com/esoteric-programmer/LMFAO

Well, I may have tolerated that, but I'm a little disappointed that the C0 is more show than real since neither the source code nor the entire tool chain were released or named. Even in the write-up, the use of LMFAO is not named at all. If you don't want to put your into GPL v3 (including a release of your source codes), please contact me to discuss the usage of the init_module.

**Comment by iczelia** [comment]
@esoteric-programmer

Interesting. When I was tinkering with your code, I didn't exactly realize that grafting the string would be a license violation. Thanks for the heads up, I will contact you as soon as possible.
